import {
  Layers,
  Scissors,
  Minimize2,
  FileText,
  FileUp,
  FileDown,
  Image as ImageIcon,
  PenLine,
  PenTool,
  Sparkles,
  ScanLine,
  Unlock,
  Lock,
  Table,
  Presentation,
  FileSpreadsheet,
  Stamp,
  RotateCw,
  Trash2,
  Code2,
  Type,
  Wrench,
  ScanText,
  Archive,
  ShieldX,
  Crop,
  FileSearch,
  type LucideIcon,
} from "lucide-react";
import { FILE_SIZE_MARKETING } from "@/config/constants";

export const ICON_MAP: Record<string, LucideIcon> = {
  Layers,
  Scissors,
  Minimize2,
  FileText,
  FileUp,
  FileDown,
  Image: ImageIcon,
  PenLine,
  PenTool,
  Sparkles,
  ScanLine,
  Unlock,
  Lock,
  Table,
  Presentation,
  FileSpreadsheet,
  Stamp,
  RotateCw,
  Trash2,
  Code2,
  Type,
  Wrench,
  ScanText,
  Archive,
  ShieldX,
  Crop,
  FileSearch,
};

export const TOOL_KEYS = [
  { slug: "merge-pdf", icon: "Layers", nameKey: "tools.mergePdf.name", descKey: "tools.mergePdf.description", category: "organize" },
  { slug: "split-pdf", icon: "Scissors", nameKey: "tools.splitPdf.name", descKey: "tools.splitPdf.description", category: "organize" },
  { slug: "rotate-pdf", icon: "RotateCw", nameKey: "tools.rotatePdf.name", descKey: "tools.rotatePdf.description", category: "organize" },
  { slug: "delete-pdf", icon: "Trash2", nameKey: "tools.deletePdf.name", descKey: "tools.deletePdf.description", category: "organize" },
  { slug: "extract-pdf", icon: "FileDown", nameKey: "tools.extractPdf.name", descKey: "tools.extractPdf.description", category: "organize" },
  { slug: "compress-pdf", icon: "Minimize2", nameKey: "tools.compressPdf.name", descKey: "tools.compressPdf.description", category: "optimize" },
  { slug: "pdf-to-word", icon: "FileText", nameKey: "tools.pdfToWord.name", descKey: "tools.pdfToWord.description", category: "convert-from" },
  { slug: "pdf-to-excel", icon: "Table", nameKey: "tools.pdfToExcel.name", descKey: "tools.pdfToExcel.description", category: "convert-from" },
  { slug: "pdf-to-ppt", icon: "Presentation", nameKey: "tools.pdfToPpt.name", descKey: "tools.pdfToPpt.description", category: "convert-from" },
  { slug: "word-to-pdf", icon: "FileUp", nameKey: "tools.wordToPdf.name", descKey: "tools.wordToPdf.description", category: "convert-to" },
  { slug: "excel-to-pdf", icon: "FileSpreadsheet", nameKey: "tools.excelToPdf.name", descKey: "tools.excelToPdf.description", category: "convert-to" },
  { slug: "ppt-to-pdf", icon: "Presentation", nameKey: "tools.pptToPdf.name", descKey: "tools.pptToPdf.description", category: "convert-to" },
  { slug: "jpg-to-pdf", icon: "Image", nameKey: "tools.jpgToPdf.name", descKey: "tools.jpgToPdf.description", category: "convert-to" },
  { slug: "html-to-pdf", icon: "Code2", nameKey: "tools.htmlToPdf.name", descKey: "tools.htmlToPdf.description", category: "convert-to" },
  { slug: "txt-to-pdf", icon: "Type", nameKey: "tools.txtToPdf.name", descKey: "tools.txtToPdf.description", category: "convert-to" },
  { slug: "edit-pdf", icon: "PenLine", nameKey: "tools.editPdf.name", descKey: "tools.editPdf.description", category: "edit" },
  { slug: "sign-pdf", icon: "PenTool", nameKey: "tools.signPdf.name", descKey: "tools.signPdf.description", category: "edit", isPro: true },
  { slug: "add-watermark", icon: "Stamp", nameKey: "tools.addWatermark.name", descKey: "tools.addWatermark.description", category: "edit" },
  { slug: "ai-pdf-summarizer", icon: "Sparkles", nameKey: "tools.aiPdfSummarizer.name", descKey: "tools.aiPdfSummarizer.description", category: "ai", isPro: true },
  { slug: "pdf-scanner", icon: "ScanLine", nameKey: "tools.pdfScanner.name", descKey: "tools.pdfScanner.description", category: "scan" },
  { slug: "unlock-pdf", icon: "Unlock", nameKey: "tools.unlockPdf.name", descKey: "tools.unlockPdf.description", category: "security" },
  { slug: "protect-pdf", icon: "Lock", nameKey: "tools.protectPdf.name", descKey: "tools.protectPdf.description", category: "security" },
  { slug: "repair-pdf", icon: "Wrench", nameKey: "tools.repairPdf.name", descKey: "tools.repairPdf.description", category: "optimize" },
  { slug: "ocr-pdf", icon: "ScanText", nameKey: "tools.ocrPdf.name", descKey: "tools.ocrPdf.description", category: "optimize" },
  { slug: "pdf-a", icon: "Archive", nameKey: "tools.pdfA.name", descKey: "tools.pdfA.description", category: "optimize" },
  { slug: "redact-pdf", icon: "ShieldX", nameKey: "tools.redactPdf.name", descKey: "tools.redactPdf.description", category: "security" },
  { slug: "crop-pdf", icon: "Crop", nameKey: "tools.cropPdf.name", descKey: "tools.cropPdf.description", category: "organize" },
  { slug: "compare-pdf", icon: "FileSearch", nameKey: "tools.comparePdf.name", descKey: "tools.comparePdf.description", category: "organize" },
] as const;

export const FAQ_KEYS = ["faq1", "faq2", "faq3", "faq4", "faq5", "faq6", "faq7"] as const;

export const FREE_FEATURES = [
  "5 tool uses per day",
  FILE_SIZE_MARKETING.freeLabel,
  "Basic PDF tools",
  "Standard processing speed",
  "Files deleted after 2 hours",
];

export const PRO_FEATURES = [
  "100 tool uses per day",
  FILE_SIZE_MARKETING.proLabel,
  "All PDF tools including Sign & AI",
  "AI PDF Summarizer",
  "Priority processing",
  "No ads",
  "Batch processing",
];

export const TOOL_CATEGORIES = [
  { id: "organize", labelKey: "landing.toolsCategoryOrganize" },
  { id: "optimize", labelKey: "landing.toolsCategoryOptimize" },
  { id: "convert-from", labelKey: "landing.toolsCategoryConvertFrom" },
  { id: "convert-to", labelKey: "landing.toolsCategoryConvertTo" },
  { id: "edit", labelKey: "landing.toolsCategoryEdit" },
  { id: "security", labelKey: "landing.toolsCategorySecurity" },
  { id: "ai", labelKey: "landing.toolsCategoryAi" },
  { id: "scan", labelKey: "landing.toolsCategoryScan" },
] as const;

export const CATEGORY_FALLBACK_LABELS: Record<string, string> = {
  organize: "Organize PDF",
  optimize: "Optimize PDF",
  "convert-from": "Convert from PDF",
  "convert-to": "Convert to PDF",
  edit: "Edit & Sign",
  security: "Security",
  ai: "AI Tools",
  scan: "Scan",
};

/** Colored icon tiles per tool category */
export const TOOL_ACCENT: Record<string, string> = {
  "merge-pdf": "bg-[#E74C3C]",
  "split-pdf": "bg-[#E67E22]",
  "rotate-pdf": "bg-[#9B59B6]",
  "delete-pdf": "bg-[#E74C3C]",
  "extract-pdf": "bg-[#3498DB]",
  "compress-pdf": "bg-[#27AE60]",
  "pdf-to-word": "bg-[#2980B9]",
  "pdf-to-excel": "bg-[#16A085]",
  "pdf-to-ppt": "bg-[#D35400]",
  "word-to-pdf": "bg-[#3498DB]",
  "excel-to-pdf": "bg-[#2ECC71]",
  "ppt-to-pdf": "bg-[#C0392B]",
  "jpg-to-pdf": "bg-[#9B59B6]",
  "html-to-pdf": "bg-[#E65100]",
  "txt-to-pdf": "bg-[#5C6BC0]",
  "sign-pdf": "bg-[#34495E]",
  "add-watermark": "bg-[#7F8C8D]",
  "ai-pdf-summarizer": "bg-[#6C5CE7]",
  "pdf-scanner": "bg-[#00B894]",
  "unlock-pdf": "bg-[#F39C12]",
  "protect-pdf": "bg-[#E84393]",
  "repair-pdf": "bg-[#0F766E]",
  "ocr-pdf": "bg-[#0369A1]",
  "pdf-a": "bg-[#7C3AED]",
  "redact-pdf": "bg-[#BE123C]",
  "crop-pdf": "bg-[#B45309]",
  "compare-pdf": "bg-[#4338CA]",
};

/** Rich gradients for 3D tool icon tiles */
export const TOOL_GRADIENT: Record<string, string> = {
  "merge-pdf": "from-rose-400 via-red-500 to-red-700",
  "split-pdf": "from-amber-400 via-orange-500 to-orange-700",
  "rotate-pdf": "from-violet-400 via-purple-500 to-purple-800",
  "delete-pdf": "from-rose-400 via-red-500 to-rose-800",
  "extract-pdf": "from-sky-400 via-blue-500 to-blue-700",
  "compress-pdf": "from-emerald-400 via-green-500 to-green-700",
  "pdf-to-word": "from-blue-400 via-blue-600 to-indigo-700",
  "pdf-to-excel": "from-teal-400 via-emerald-500 to-teal-700",
  "pdf-to-ppt": "from-orange-400 via-orange-600 to-red-700",
  "word-to-pdf": "from-sky-400 via-blue-500 to-blue-700",
  "excel-to-pdf": "from-green-400 via-emerald-500 to-green-700",
  "ppt-to-pdf": "from-red-400 via-red-600 to-rose-800",
  "jpg-to-pdf": "from-fuchsia-400 via-purple-500 to-violet-700",
  "html-to-pdf": "from-orange-400 via-amber-600 to-orange-800",
  "txt-to-pdf": "from-indigo-400 via-indigo-500 to-indigo-700",
  "sign-pdf": "from-slate-500 via-slate-700 to-slate-900",
  "add-watermark": "from-gray-400 via-gray-500 to-gray-700",
  "ai-pdf-summarizer": "from-violet-400 via-purple-500 to-indigo-700",
  "pdf-scanner": "from-teal-400 via-emerald-500 to-cyan-700",
  "unlock-pdf": "from-amber-400 via-yellow-500 to-orange-600",
  "protect-pdf": "from-pink-400 via-rose-500 to-pink-700",
  "edit-pdf": "from-cyan-400 via-blue-500 to-blue-700",
  "repair-pdf": "from-teal-400 via-teal-600 to-slate-800",
  "ocr-pdf": "from-sky-400 via-blue-600 to-cyan-800",
  "pdf-a": "from-violet-400 via-violet-600 to-indigo-800",
  "redact-pdf": "from-rose-400 via-rose-700 to-slate-900",
  "crop-pdf": "from-amber-400 via-orange-600 to-amber-800",
  "compare-pdf": "from-indigo-400 via-indigo-600 to-blue-900",
};
