#!/usr/bin/env python3
"""Phase 3.4: synthetic scanner artifacts through loopback HTTP only.

Pillow defines the source/orientation oracle; MuPDF extracts downloaded pixels;
Poppler independently renders PDFs. The app's Sharp code is never imported.
"""
from __future__ import annotations

import argparse
import hashlib
import http.cookiejar
import io
import json
import re
import shutil
import subprocess
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path

import fitz
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = ROOT / "tmp/pdfs/phase3-scanner"
REPORT_ROOT = ROOT / "quality/phase3-scanner"
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
ROUTE = "/api/tools/pdf-scanner"


def label(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def validate_base_url(value: str) -> str:
    parsed = urllib.parse.urlsplit(value)
    if (parsed.scheme != "http" or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}
            or parsed.username or parsed.password or parsed.path not in {"", "/"}
            or parsed.query or parsed.fragment):
        raise ValueError("Only a loopback HTTP origin without credentials is allowed")
    _ = parsed.port
    return value.rstrip("/")


class RejectRedirects(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        raise ValueError(f"Redirect rejected (HTTP {code})")


class LocalTransport:
    def __init__(self, base: str):
        self.base = validate_base_url(base)
        self.opener = urllib.request.build_opener(
            urllib.request.ProxyHandler({}),
            urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()),
            RejectRedirects(),
        )

    def post(self, files: list[dict], filter_value: str) -> tuple[int, bytes, dict, float]:
        boundary = "onlymypdf-scanner-" + uuid.uuid4().hex
        fields = []
        for file in files:
            # Filenames are controlled literals generated by this runner.
            fields.append((f'--{boundary}\r\nContent-Disposition: form-data; name="files"; '
                           f'filename="{file["path"].name}"\r\nContent-Type: {file["mime"]}\r\n\r\n')
                          .encode("ascii") + file["path"].read_bytes() + b"\r\n")
        fields.append((f'--{boundary}\r\nContent-Disposition: form-data; name="filter"\r\n\r\n'
                       f'{filter_value}\r\n--{boundary}--\r\n').encode("ascii"))
        payload = b"".join(fields)
        request = urllib.request.Request(self.base + ROUTE, data=payload, method="POST", headers={
            "Origin": self.base,
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "User-Agent": "OnlyMyPDF-local-scanner-corpus/1",
        })
        start = time.monotonic()
        try:
            response = self.opener.open(request, timeout=60)
        except urllib.error.HTTPError as error:
            response = error
        with response:
            body = response.read(20 * 1024 * 1024 + 1)
            if len(body) > 20 * 1024 * 1024:
                raise ValueError("Scanner response exceeds 20 MiB diagnostic limit")
            return response.code, body, {k.lower(): v for k, v in response.headers.items()}, time.monotonic() - start


def font(size: int):
    for path in (Path("C:/Windows/Fonts/arial.ttf"), Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")):
        if path.is_file():
            return ImageFont.truetype(str(path), size)
    raise FileNotFoundError("A local Arial or DejaVu Sans font is required; nothing is downloaded")


def page_image(number: int, color: tuple[int, int, int]) -> Image.Image:
    image = Image.new("RGB", (640, 880), "white")
    draw = ImageDraw.Draw(image)
    draw.rectangle((35, 35, 604, 145), fill=color)
    draw.text((55, 67), f"SCANNER PAGE {number:02d}", fill="white", font=font(36))
    draw.text((45, 195), "Synthetic English scan", fill=(20, 25, 35), font=font(28))
    draw.text((45, 247), "TOP LEFT reference", fill=(20, 25, 35), font=font(23))
    draw.rectangle((45, 300, 210, 440), fill=(195, 35, 45))
    draw.rectangle((240, 300, 405, 440), fill=(30, 145, 55))
    draw.rectangle((435, 300, 594, 440), fill=(35, 65, 205))
    draw.text((45, 485), f"Item ID 00{number:03d}", fill=(20, 25, 35), font=font(29))
    draw.text((45, 535), f"Amount {100 + number}.25 USD", fill=(20, 25, 35), font=font(29))
    draw.text((45, 620), "Keep every image in upload order.", fill=(20, 25, 35), font=font(24))
    draw.rectangle((380, 742, 594, 834), fill=color)
    draw.text((402, 771), "BOTTOM RIGHT", fill="white", font=font(19))
    return image


def write_source(directory: Path, name: str, image: Image.Image, format_name: str,
                 exif_orientation: int | None = None) -> dict:
    extensions = {"PNG": "png", "JPEG": "jpg", "WEBP": "webp"}
    mime = {"PNG": "image/png", "JPEG": "image/jpeg", "WEBP": "image/webp"}[format_name]
    target = directory / f"{name}.{extensions[format_name]}"
    save_options = {"JPEG": {"quality": 96, "subsampling": 0}, "WEBP": {"lossless": True}, "PNG": {}}[format_name]
    if exif_orientation is not None:
        exif = Image.Exif()
        exif[274] = exif_orientation
        save_options = {**save_options, "exif": exif.tobytes()}
    image.save(target, format_name, **save_options)
    with Image.open(target) as reopened:
        stored_size = reopened.size
        actual_orientation = reopened.getexif().get(274, 1)
        expected = ImageOps.exif_transpose(reopened).convert("RGB")
    preview = directory / f"{name}-expected-upright.png"
    expected.save(preview)
    return {"path": target, "mime": mime, "format": format_name, "expected": expected,
            "source": {"path": label(target), "sha256": sha256(target.read_bytes()),
                       "format": format_name, "storedPixels": list(stored_size),
                       "orientation": actual_orientation, "expectedPixels": list(expected.size),
                       "expectedDecodedPixelSha256": sha256(expected.tobytes()), "previewPath": label(preview)}}


def make_fixtures(directory: Path) -> tuple[list[dict], list[dict]]:
    directory.mkdir(parents=True)
    original = write_source(directory, "original-color", page_image(1, (26, 83, 160)), "PNG")
    bw = Image.new("RGB", (640, 880), "white")
    draw = ImageDraw.Draw(bw)
    draw.text((36, 40), "BLACK AND WHITE CHECK", fill="black", font=font(29))
    draw.text((36, 90), "128 threshold, exact gray source", fill="black", font=font(23))
    levels = [0, 32, 64, 96, 120, 127, 128, 136, 160, 192, 224, 255]
    for index, level in enumerate(levels):
        y = 170 + index * 46
        draw.rectangle((40, y, 600, y + 43), fill=(level,) * 3)
        draw.text((53, y + 7), f"LEVEL {level:03d}", fill="white" if level < 128 else "black", font=font(23))
    draw.text((36, 780), "END OF BINARY TEST", fill="black", font=font(27))
    binary = write_source(directory, "bw-gray-levels", bw, "PNG")

    enhanced = Image.new("RGB", (640, 880), (174,) * 3)
    draw = ImageDraw.Draw(enhanced)
    draw.text((36, 40), "LOW CONTRAST SOURCE", fill=(122,) * 3, font=font(31))
    draw.text((36, 100), "Enhanced should change contrast.", fill=(125,) * 3, font=font(23))
    for index, level in enumerate((125, 137, 149, 161)):
        y = 185 + index * 130
        draw.rectangle((45, y, 595, y + 104), fill=(level,) * 3)
        draw.text((63, y + 36), f"PATCH {index + 1} / ORIGINAL {level}", fill=(174,) * 3, font=font(25))
    draw.text((36, 770), "FINAL LINE 00731 / 81.25 USD", fill=(122,) * 3, font=font(24))
    low_contrast = write_source(directory, "enhanced-low-contrast", enhanced, "PNG")

    upright = page_image(6, (117, 58, 155))
    exif = write_source(directory, "phone-exif-6", upright.transpose(Image.Transpose.ROTATE_90), "JPEG", 6)
    colors = [(25, 85, 160), (145, 45, 60), (30, 115, 65), (120, 60, 155), (150, 90, 25),
              (15, 120, 140), (70, 70, 140), (140, 40, 110), (100, 110, 30), (40, 105, 110)]
    mixed = [write_source(directory, f"mixed-{index + 1:02d}", page_image(index + 1, color),
                          ["PNG", "JPEG", "WEBP"][index % 3]) for index, color in enumerate(colors)]
    positive = [
        {"caseId": "original-color-png", "filter": "original", "files": [original], "check": "original"},
        {"caseId": "bw-gray-levels", "filter": "bw", "files": [binary], "check": "bw"},
        {"caseId": "enhanced-low-contrast", "filter": "enhanced", "files": [low_contrast], "check": "enhanced"},
        {"caseId": "exif-6-upright-jpeg", "filter": "original", "files": [exif], "check": "original"},
        {"caseId": "ten-mixed-pages-in-order", "filter": "original", "files": mixed, "check": "original"},
    ]
    text_path = directory / "not-an-image.txt"
    text_path.write_text("Synthetic plain text, not an image.", encoding="utf-8")
    corrupt_path = directory / "truncated-image.png"
    corrupt_path.write_bytes(PNG_MAGIC)
    corrupt = {"path": corrupt_path, "mime": "image/png"}
    negative = [
        {"caseId": "reject-eleven-images", "filter": "original", "files": [*mixed, original], "error": "10 images"},
        {"caseId": "reject-unknown-filter", "filter": "unknown-filter", "files": [original], "error": "filter"},
        {"caseId": "reject-no-images", "filter": "original", "files": [], "error": "image"},
        {"caseId": "reject-non-image", "filter": "original", "files": [{"path": text_path, "mime": "text/plain"}], "error": "file"},
        {"caseId": "reject-truncated-image", "filter": "original", "files": [corrupt], "error": "image"},
        {"caseId": "reject-entire-mixed-corrupt-batch", "filter": "original", "files": [original, corrupt], "error": "image"},
    ]
    return positive, negative


def validate_pixels(actual: Image.Image, expected: Image.Image, check: str, format_name: str) -> dict:
    assert actual.size == expected.size, f"Embedded dimensions {actual.size} != oriented source {expected.size}"
    pixels = np.asarray(actual.convert("RGB"), dtype=np.int16)
    reference = np.asarray(expected.convert("RGB"), dtype=np.int16)
    if check == "bw":
        assert np.array_equal(reference[:, :, 0], reference[:, :, 1])
        assert np.array_equal(reference[:, :, 1], reference[:, :, 2])
        binary = np.where(reference >= 128, 255, 0)
        unequal = int(np.count_nonzero(pixels != binary))
        levels = np.unique(pixels).tolist()
        assert levels == [0, 255], f"B&W pixels are not binary: {levels[:16]}"
        assert unequal == 0, f"B&W threshold differs from literal grayscale source in {unequal} channels"
        return {"passed": True, "method": "Exact threshold of independent grayscale source pixels", "threshold": 128,
                "pixelLevels": levels, "differentChannels": unequal}
    difference = np.abs(pixels - reference)
    if check == "enhanced":
        before_range = float(np.percentile(reference[:, :, 0], 95) - np.percentile(reference[:, :, 0], 5))
        after_range = float(np.percentile(pixels[:, :, 0], 95) - np.percentile(pixels[:, :, 0], 5))
        mean_difference = float(difference.mean())
        assert mean_difference > 10, f"Enhanced unchanged or negligible change: {mean_difference}"
        assert after_range >= before_range * 1.5, f"Expected greater measured contrast: {before_range} -> {after_range}"
        # Test broad literal patches away from edges, not Sharp's implementation.
        patch_means = [float(pixels[y + 10:y + 28, 60:570].mean()) for y in [185, 315, 445, 575]]
        assert all(a < b for a, b in zip(patch_means, patch_means[1:])), "Enhanced reversed the ordered gray patches"
        return {"passed": True, "method": "Low-contrast fixture changed and retained ordered gray patches",
                "meanAbsoluteChannelDifference": mean_difference, "sourceP95P5Range": before_range,
                "outputP95P5Range": after_range, "orderedPatchMeans": patch_means,
                "limitations": "Demonstrates this filter changed this fixture; does not prove readability on every photo."}
    mean_difference, maximum = float(difference.mean()), int(difference.max())
    if format_name == "JPEG":
        # Pillow/libjpeg and libvips JPEG decoders may round color conversion
        # differently; no lossy output re-encoding is allowed after decoding.
        assert mean_difference <= 1 and maximum <= 8, f"JPEG decoder/orientation mismatch: mean={mean_difference}, max={maximum}"
        tolerance = {"meanAbsoluteChannelDifferenceMax": 1, "singleChannelDifferenceMax": 8,
                     "reason": "Independent Pillow and app JPEG decoder color rounding; fixture uses 4:4:4 sampling."}
    else:
        assert maximum == 0, f"Lossless {format_name} pixels changed: max channel difference {maximum}"
        tolerance = {"singleChannelDifferenceMax": 0}
    return {"passed": True, "method": "Independent Pillow decoded, EXIF-transposed source compared pixelwise",
            "meanAbsoluteChannelDifference": mean_difference, "maximumChannelDifference": maximum,
            "tolerance": tolerance}


def inspect_pdf(body: bytes, case: dict, output: Path) -> dict:
    assert body.startswith(b"%PDF-"), "Missing PDF magic"
    pages = []
    with fitz.open(stream=body, filetype="pdf") as pdf:
        assert not pdf.is_encrypted, "Unexpected encrypted result"
        assert len(pdf) == len(case["files"]), f"Expected {len(case['files'])} pages, got {len(pdf)}"
        for index, page in enumerate(pdf):
            source = case["files"][index]
            assert abs(page.rect.width - 595.28) <= .05 and abs(page.rect.height - 841.89) <= .05, "Unexpected A4 portrait output geometry"
            assert not page.get_text().strip(), "Scanner unexpectedly added selectable text"
            images = page.get_images(full=True)
            assert len(images) == 1, f"Page {index + 1}: expected one image, got {len(images)}"
            xref = images[0][0]
            extracted = pdf.extract_image(xref)
            with Image.open(io.BytesIO(extracted["image"])) as decoded:
                actual = decoded.convert("RGB")
            embedded = output.parent / f"{case['caseId']}-embedded-{index + 1:02d}.png"
            actual.save(embedded)
            check = validate_pixels(actual, source["expected"], case["check"], source["format"])
            rectangles = page.get_image_rects(xref)
            assert len(rectangles) == 1, "Image unexpectedly drawn more than once"
            scale = min((page.rect.width - 40) / actual.width, (page.rect.height - 40) / actual.height, 1)
            w, h = actual.width * scale, actual.height * scale
            expected_rect = [(page.rect.width - w) / 2, (page.rect.height - h) / 2,
                             (page.rect.width + w) / 2, (page.rect.height + h) / 2]
            assert max(abs(a - b) for a, b in zip(rectangles[0], expected_rect)) <= .05, "Image aspect, fit or centering changed"
            pages.append({"page": index + 1, "sourcePath": source["source"]["path"],
                          "widthPoints": page.rect.width, "heightPoints": page.rect.height,
                          "embeddedPixels": list(actual.size), "embeddedPreviewPath": label(embedded),
                          "imageBoundsPoints": list(rectangles[0]), "selectableTextCharacters": 0,
                          "pixelCheck": check, "passed": True})
    return {"passed": True, "pageCount": len(pages), "pages": pages,
            "pageOrderMethod": "Each embedded page is compared to its same-index literal source, including distinct page number and color patches."}


def render_pdf(pdf_path: Path, case_id: str) -> list[str]:
    executable = shutil.which("pdftoppm")
    if not executable:
        raise FileNotFoundError("Local Poppler pdftoppm is required; no download is performed")
    prefix = pdf_path.parent / f"{case_id}-output"
    completed = subprocess.run([executable, "-png", "-r", "96", str(pdf_path), str(prefix)],
                               capture_output=True, text=True, timeout=45)
    if completed.returncode:
        raise RuntimeError(f"Poppler render failed: {completed.stderr[:300]}")
    paths = sorted(pdf_path.parent.glob(f"{case_id}-output-*.png"), key=lambda p: int(p.stem.rsplit("-", 1)[1]))
    return [label(p) for p in paths]


def run_case(transport: LocalTransport, case: dict, destination: Path, negative: bool) -> dict:
    result = {"caseId": case["caseId"], "filter": case["filter"], "inputFiles": len(case["files"]),
              "kind": "negative" if negative else "positive"}
    try:
        status, body, headers, seconds = transport.post(case["files"], case["filter"])
        result.update(httpStatus=status, contentType=headers.get("content-type", ""), outputBytes=len(body),
                      responseSha256=sha256(body), httpSeconds=round(seconds, 3))
        if negative:
            assert status == 400, f"Expected HTTP 400 for invalid input, got {status}"
            assert "application/json" in result["contentType"], "Invalid input did not return JSON"
            assert not body.startswith(b"%PDF-"), "Invalid batch returned partial PDF"
            payload = json.loads(body)
            message = payload.get("error", "")
            assert isinstance(message, str) and case["error"] in message.lower(), f"Unhelpful error: {message}"
            result.update(error=message, noPdfArtifact=True)
        else:
            assert status == 200, f"Expected PDF success, got HTTP {status}: {body[:240]!r}"
            assert result["contentType"].split(";", 1)[0].strip() == "application/pdf", "Wrong PDF MIME"
            assert 'filename="scanned-document.pdf"' in headers.get("content-disposition", ""), "Missing PDF download filename"
            if "content-length" in headers:
                assert int(headers["content-length"]) == len(body), "Response byte count differs from Content-Length"
            output = destination / f"{case['caseId']}-result.pdf"
            output.write_bytes(body)
            result["outputPath"] = label(output)
            result["validation"] = inspect_pdf(body, case, output)
            result["renderedPreviewPaths"] = render_pdf(output, case["caseId"])
            assert len(result["renderedPreviewPaths"]) == len(case["files"]), "Independent renderer page count differs"
        result["status"] = "passed"
    except Exception as error:
        result.update(status="failed", failure=str(error))
    return result


def contact_sheet(results: list[dict], destination: Path) -> str | None:
    previews = [(r["caseId"], p) for r in results for p in r.get("renderedPreviewPaths", [])]
    if not previews:
        return None
    columns, cell_width, cell_height = 4, 245, 380
    sheet = Image.new("RGB", (columns * cell_width, ((len(previews) + columns - 1) // columns) * cell_height), (232, 237, 242))
    draw = ImageDraw.Draw(sheet)
    for index, (name, path) in enumerate(previews):
        with Image.open(ROOT / path) as image:
            image = image.convert("RGB")
            image.thumbnail((cell_width - 14, cell_height - 45))
            x, y = index % columns * cell_width, index // columns * cell_height
            draw.text((x + 7, y + 6), name[:31], fill=(25, 35, 50), font=font(12))
            sheet.paste(image, (x + (cell_width - image.width) // 2, y + 29))
    path = destination / "output-contact-sheet.png"
    sheet.save(path)
    return label(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", default="http://127.0.0.1:3001")
    parser.add_argument("--run-label", required=True, help="Fresh label; existing reports/artifacts are never overwritten")
    parser.add_argument("--generate-only", action="store_true")
    args = parser.parse_args()
    base = validate_base_url(args.base_url)
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]{0,63}", args.run_label):
        parser.error("Use a lowercase alphanumeric/hyphen run label")
    destination = ARTIFACT_ROOT / args.run_label
    report_path = REPORT_ROOT / f"{args.run_label}-report.json"
    if destination.exists() or report_path.exists():
        parser.error("Run label already exists; choose a fresh label")
    positive, negative = make_fixtures(destination / "sources")
    report = {"schemaVersion": 1, "phase": "3.4", "generatedAt": datetime.now(timezone.utc).isoformat(),
              "runLabel": args.run_label, "baseUrl": base, "generateOnly": args.generate_only,
              "validatorSha256": sha256(Path(__file__).read_bytes()),
              "method": "Actual loopback HTTP; Pillow source and EXIF oracle; MuPDF PDF/image extraction; independent Poppler 96 DPI output renders. No app processing code imported.",
              "limitations": ["Synthetic static JPG/PNG/WebP images only; no real-customer acceptance, handwriting, OCR, animation, automatic crop or perspective-correction claim.",
                              "Enhanced checks measure a deliberate low-contrast fixture, not universal readability or quality improvement.",
                              "JPEG allows independent decoder rounding only (mean channel difference <=1, max<=8); lossless PNG/WebP and grayscale B&W thresholds require exact pixels.",
                              "All source and output previews need separate visual inspection; HTTP timings are individual local observations.",
                              "No cloud requests, paid services, browser actions, source code changes, response redirects or configured HTTP proxies are used."],
              "sources": [{"caseId": c["caseId"], "filter": c["filter"], "check": c["check"],
                           "files": [f["source"] for f in c["files"]]} for c in positive], "results": []}
    if not args.generate_only:
        transport = LocalTransport(base)
        for negative_case, cases in [(False, positive), (True, negative)]:
            for case in cases:
                result = run_case(transport, case, destination, negative_case)
                report["results"].append(result)
                print(json.dumps({"caseId": case["caseId"], "status": result["status"],
                                  "httpStatus": result.get("httpStatus"), "failure": result.get("failure")}), flush=True)
    results = report["results"]
    report["summary"] = {"positiveCases": len(positive), "negativeCases": len(negative),
                         "routesTested": len(results), "passed": sum(r["status"] == "passed" for r in results),
                         "failed": sum(r["status"] != "passed" for r in results),
                         "renderedPages": sum(len(r.get("renderedPreviewPaths", [])) for r in results),
                         "allPassed": len(results) == len(positive) + len(negative) and all(r["status"] == "passed" for r in results)}
    report["outputContactSheet"] = contact_sheet(results, destination)
    REPORT_ROOT.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"report": label(report_path), "summary": report["summary"],
                      "outputContactSheet": report["outputContactSheet"]}), flush=True)
    return 0 if args.generate_only or report["summary"]["allPassed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
